# Generated by Django 5.1.4 on 2025-02-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_avaliation'),
    ]

    operations = [
    ]
