# Generated by Django 5.1.4 on 2025-02-24 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250224_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product'),
        ),
    ]
